import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FlowersStockWebService", targetNamespace = "http://business.be.flowershop.accenture.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FlowersStockWebService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "increaseFlowersStockSize", targetNamespace = "http://business.be.flowershop.accenture.com/", className = "com.accenture.flowershop.be.business.IncreaseFlowersStockSize")
    @ResponseWrapper(localName = "increaseFlowersStockSizeResponse", targetNamespace = "http://business.be.flowershop.accenture.com/", className = "com.accenture.flowershop.be.business.IncreaseFlowersStockSizeResponse")
    public void increaseFlowersStockSize(
            @WebParam(name = "arg0", targetNamespace = "")
                    int arg0);

}
