import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "flowersStockWebService", targetNamespace = "http://business.be.flowershop.accenture.com/", wsdlLocation = "http://localhost:8080/ws/flowersStockWebService?wsdl")
public class FlowersStockWebService_Service
    extends Service
{

    private final static URL FLOWERSSTOCKWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException FLOWERSSTOCKWEBSERVICE_EXCEPTION;
    private final static QName FLOWERSSTOCKWEBSERVICE_QNAME = new QName("http://business.be.flowershop.accenture.com/", "flowersStockWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/flowersStockWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FLOWERSSTOCKWEBSERVICE_WSDL_LOCATION = url;
        FLOWERSSTOCKWEBSERVICE_EXCEPTION = e;
    }

    public FlowersStockWebService_Service() {
        super(__getWsdlLocation(), FLOWERSSTOCKWEBSERVICE_QNAME);
    }

    public FlowersStockWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), FLOWERSSTOCKWEBSERVICE_QNAME, features);
    }

    public FlowersStockWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, FLOWERSSTOCKWEBSERVICE_QNAME);
    }

    public FlowersStockWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FLOWERSSTOCKWEBSERVICE_QNAME, features);
    }

    public FlowersStockWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FlowersStockWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FlowersStockWebService
     */
    @WebEndpoint(name = "FlowersStockWebServiceImplPort")
    public FlowersStockWebService getFlowersStockWebServiceImplPort() {
        return super.getPort(new QName("http://business.be.flowershop.accenture.com/", "FlowersStockWebServiceImplPort"), FlowersStockWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlowersStockWebService
     */
    @WebEndpoint(name = "FlowersStockWebServiceImplPort")
    public FlowersStockWebService getFlowersStockWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://business.be.flowershop.accenture.com/", "FlowersStockWebServiceImplPort"), FlowersStockWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FLOWERSSTOCKWEBSERVICE_EXCEPTION!= null) {
            throw FLOWERSSTOCKWEBSERVICE_EXCEPTION;
        }
        return FLOWERSSTOCKWEBSERVICE_WSDL_LOCATION;
    }

}
